set_property SRC_FILE_INFO {cfile:/home/libano/vivado/non_project_mode/systolic_8x8/systolic_8x8/systolic_8x8.srcs/constrs_1/new/xdc.xdc rfile:../systolic_8x8/systolic_8x8.srcs/constrs_1/new/xdc.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
create_clock -name clk_wiz_0_clk_out1 -period 5 [get_pins clk]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
create_clock -name clk_wiz_0_clk_out2 -period 2.5 [get_pins clk2x]
