# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/import_me/dsp_macro.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dsp_macro || ORIG_REF_NAME==dsp_macro} -quiet] -quiet

# IP: bd/import_me/ip/dsp_macro_xbip_dsp48_macro_0_0/dsp_macro_xbip_dsp48_macro_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dsp_macro_xbip_dsp48_macro_0_0 || ORIG_REF_NAME==dsp_macro_xbip_dsp48_macro_0_0} -quiet] -quiet

# XDC: bd/import_me/dsp_macro_ooc.xdc
