# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/libano/github/SystolicArray/generator/RTL/ip/dsp_macro_xbip_dsp48_macro_0_0/dsp_macro_xbip_dsp48_macro_0_0.xci
# IP: The module: 'dsp_macro_xbip_dsp48_macro_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/libano/github/SystolicArray/generator/RTL/ip/dsp_macro_xbip_dsp48_macro_0_0/dsp_macro_xbip_dsp48_macro_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dsp_macro_xbip_dsp48_macro_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/libano/github/SystolicArray/generator/RTL/ip/dsp_macro_xbip_dsp48_macro_0_0/dsp_macro_xbip_dsp48_macro_0_0.xci
# IP: The module: 'dsp_macro_xbip_dsp48_macro_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/libano/github/SystolicArray/generator/RTL/ip/dsp_macro_xbip_dsp48_macro_0_0/dsp_macro_xbip_dsp48_macro_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dsp_macro_xbip_dsp48_macro_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
